### ISSUE TITLE
Getting error - Warning: unlink(test/wordtemplatedownload/vt_0044270001421699603971)

### ISSUE THREAD

**Issue by jayo2005** [techblue/vtiger-libreoffice-mailmerge#6]
I am gettng following error

Warning: unlink(test/wordtemplatedownload/vt_0044270001421699603971): Is a directory in /home/leisures/public_html/vtiger/modules/MailMerge/views/createMergeHelpDesk.php on line 333

**Comment by gurvinderdadyala** [comment]
@jayo2005 Thank you for reporting bug. In order to troubleshoot further I would to get some information. 
- Vtiger Version
- PHP version
- Module in which you are getting error doing mail merge.
- Is it only showing warning or also affecting mail merge process.
- How can i replicate, If you can provide steps.

**Comment by gurvinderdadyala** [comment]
@jayo2005 Development team has identified the issue and will soon upload fix.

**Comment by gurvinderdadyala** [comment]
@jayo2005 Issue has been fixed in release version 1.0.2

**Comment by jayo2005** [comment]
Thanks I will give it a shot.
